k0s:
    version: v1.34.3+k0s.0
    api:
        address: 172.31.3.124
        port: 6443
    network:
        provider: calico
        podCIDR: 10.244.0.0/16
        serviceCIDR: 10.96.0.0/12
    storage:
        type: etcd
        etcd:
            peerAddress: 127.0.0.1
k0rdent:
    version: 1.6.0
    helm:
        chart: oci://ghcr.io/k0rdent/kcm/charts/kcm
        namespace: kcm-system
        values:
            replicas: 1
logLevel: info
